### PR TITLE
Upgrade to PyMongo 4+ and add GitHub Actions Testing

### PR DESCRIPTION
**Pull request by blink1073**
- Passing evergreen build [here](https://spruce.mongodb.com/version/640b4d513066151c5feb8e54/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) (there are some failures that were already existing).
- Passing GitHub Actions build  on my fork [here](https://github.com/blink1073/mongo-orchestration/actions/runs/4386637762).

### CODE REVIEW

**Comment by blink1073** [comment]
Once this is approved I'll open an issue to address skipped tests before merging.

**Comment by ShaneHarvey** [comment]
This test is failing with an odd error now: https://spruce.mongodb.com/task/mongo_python_driver_tests_windows_python_version_32_bit__platform~windows_64_vsMulti_small_auth_ssl~auth_ssl_python_version_windows_32~3.11_test_4.4_replica_set_patch_5e203bea8dd8cfd6d6dd9f238656976194e6c769_640b4d513066151c5feb8e54_23_03_10_15_33_13/logs?execution=0&sortBy=STATUS&sortDir=ASC

```python
 [2023/03/10 15:44:00.030] Traceback (most recent call last):
 [2023/03/10 15:44:00.030]   File "C:\data\mci\266314a5a745be4151ffd0b7a51d3a57\src\setup.py", line 315, in <module>
 [2023/03/10 15:44:00.030]     setup(
 [2023/03/10 15:44:00.030]   File "C:\python\32\Python311\Lib\site-packages\setuptools\__init__.py", line 87, in setup
 [2023/03/10 15:44:00.031]     return distutils.core.setup(**attrs)
 [2023/03/10 15:44:00.031]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 [2023/03/10 15:44:00.031]   File "C:\python\32\Python311\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
 [2023/03/10 15:44:00.032]     return run_commands(dist)
 [2023/03/10 15:44:00.032]            ^^^^^^^^^^^^^^^^^^
 [2023/03/10 15:44:00.032]   File "C:\python\32\Python311\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
 [2023/03/10 15:44:00.032]     dist.run_commands()
 [2023/03/10 15:44:00.032]   File "C:\python\32\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
 [2023/03/10 15:44:00.033]     self.run_command(cmd)
 [2023/03/10 15:44:00.033]   File "C:\python\32\Python311\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
 [2023/03/10 15:44:00.034]     super().run_command(command)
 [2023/03/10 15:44:00.034]   File "C:\python\32\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
 [2023/03/10 15:44:00.035]     cmd_obj.run()
 [2023/03/10 15:44:00.035]   File "C:\data\mci\266314a5a745be4151ffd0b7a51d3a57\src\setup.py", line 125, in run
 [2023/03/10 15:44:00.036]     result = runner.run(suite)
 [2023/03/10 15:44:00.036]              ^^^^^^^^^^^^^^^^^
 [2023/03/10 15:44:00.036]   File "C:\data\mci\266314a5a745be4151ffd0b7a51d3a57\src\test\__init__.py", line 1248, in run
 [2023/03/10 15:44:00.037]     setup()
 [2023/03/10 15:44:00.037]   File "C:\data\mci\266314a5a745be4151ffd0b7a51d3a57\src\test\__init__.py", line 1157, in setup
 [2023/03/10 15:44:00.039]     client_context.init()
 [2023/03/10 15:44:00.039]   File "C:\data\mci\266314a5a745be4151ffd0b7a51d3a57\src\test\__init__.py", line 493, in init
 [2023/03/10 15:44:00.039]     self._init_client()
 [2023/03/10 15:44:00.039]   File "C:\data\mci\266314a5a745be4151ffd0b7a51d3a57\src\test\__init__.py", line 398, in _init_client
 [2023/03/10 15:44:00.039]     if not self._check_user_provided():
 [2023/03/10 15:44:00.039]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 [2023/03/10 15:44:00.039]   File "C:\data\mci\266314a5a745be4151ffd0b7a51d3a57\src\test\__init__.py", line 544, in _check_user_provided
 [2023/03/10 15:44:00.040]     return db_user in _all_users(client.admin)
 [2023/03/10 15:44:00.040]                       ^^^^^^^^^^^^^^^^^^^^^^^^
 [2023/03/10 15:44:00.040]   File "C:\data\mci\266314a5a745be4151ffd0b7a51d3a57\src\test\__init__.py", line 253, in _all_users
 [2023/03/10 15:44:00.041]     return set(u["user"] for u in db.command("usersInfo").get("users", []))
 [2023/03/10 15:44:00.041]                                   ^^^^^^^^^^^^^^^^^^^^^^^
 [2023/03/10 15:44:00.041]   File "C:\data\mci\266314a5a745be4151ffd0b7a51d3a57\src\pymongo\_csot.py", line 106, in csot_wrapper
 [2023/03/10 15:44:00.041]     return func(self, *args, **kwargs)
 [2023/03/10 15:44:00.041]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 [2023/03/10 15:44:00.041]   File "C:\data\mci\266314a5a745be4151ffd0b7a51d3a57\src\pymongo\database.py", line 820, in command
 [2023/03/10 15:44:00.042]     with self.__client._socket_for_reads(read_preference, session) as (
 [2023/03/10 15:44:00.042]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 [2023/03/10 15:44:00.042]   File "C:\data\mci\266314a5a745be4151ffd0b7a51d3a57\src\pymongo\mongo_client.py", line 1307, in _socket_for_reads
 [2023/03/10 15:44:00.043]     server = self._select_server(read_preference, session)
 [2023/03/10 15:44:00.043]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 [2023/03/10 15:44:00.043]   File "C:\data\mci\266314a5a745be4151ffd0b7a51d3a57\src\pymongo\mongo_client.py", line 1268, in _select_server
 [2023/03/10 15:44:00.044]     server = topology.select_server(server_selector)
 [2023/03/10 15:44:00.044]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 [2023/03/10 15:44:00.044]   File "C:\data\mci\266314a5a745be4151ffd0b7a51d3a57\src\pymongo\topology.py", line 272, in select_server
 [2023/03/10 15:44:00.044]     server = self._select_server(selector, server_selection_timeout, address)
 [2023/03/10 15:44:00.044]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 [2023/03/10 15:44:00.044]   File "C:\data\mci\266314a5a745be4151ffd0b7a51d3a57\src\pymongo\topology.py", line 261, in _select_server
 [2023/03/10 15:44:00.044]     servers = self.select_servers(selector, server_selection_timeout, address)
 [2023/03/10 15:44:00.044]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 [2023/03/10 15:44:00.044]   File "C:\data\mci\266314a5a745be4151ffd0b7a51d3a57\src\pymongo\topology.py", line 223, in select_servers
 [2023/03/10 15:44:00.045]     server_descriptions = self._select_servers_loop(selector, server_timeout, address)
 [2023/03/10 15:44:00.045]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 [2023/03/10 15:44:00.045]   File "C:\data\mci\266314a5a745be4151ffd0b7a51d3a57\src\pymongo\topology.py", line 238, in _select_servers_loop
 [2023/03/10 15:44:00.045]     raise ServerSelectionTimeoutError(
 [2023/03/10 15:44:00.046] pymongo.errors.ServerSelectionTimeoutError: No replica set members match selector "Primary()", Timeout: 0.1s, Topology Description: <TopologyDescription id: 640b503fb4ecf298ce069d4f, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('localhost', 27017) server_type: RSSecondary, rtt: 0.0>, <ServerDescription ('localhost', 27018) server_type: Unknown, rtt: None>, <ServerDescription ('localhost', 27019) server_type: RSArbiter, rtt: 0.0>]>
 [2023/03/10 15:44:00.703] Command 'shell.exec' in function 'run tests' failed: shell script encountered problem: exit code 1.
```

IIRC we can't upgrade MO to pymongo 4 until all drivers stop supporting old branches that need to test against MongoDB < 3.6. Could you send a poll to see if any team still needs to test against MongoDB 3.4 or lower?

**Comment by blink1073** [comment]
I ran that build two more times and did not see the error again.

**Review by ShaneHarvey — APPROVED** [review]
Nice! Just one minor comment. After merging let's send an announcement that we've dropped support for Python < 3.7 and MongoDB < 3.6 so teams can look out for possible failures on old platforms.

**Pull request merged**
