### PR TITLE
Put server logs into the dbpath by default.

### PR DESCRIPTION
**Pull request by lovett89**
Addresses #170 

Mongos logs go into a directory created by `tempfile.mkdtemp` by default.

### CODE REVIEW

**Comment by amidvidy** [comment]
i think for this to be useful we need two more things.

1) an option to MO (config or CLI) to keep data directories around rather than removing them in cleanup_mprocess

2) we should also pass --logappend by default for tests that stop/start servers

**Comment by lovett89** [comment]
I'm not sure that I understand the purpose of (1). Why is this necessary? Why not just move or copy the logs to where they're needed, or, even better, specify the path where they're needed in the request? As another alternative, you could copy/move the logs before shutting down mongo orchestration. Do you need the data directories themselves?

**Comment by lovett89** [comment]
The `logappend` option is default now.

**Comment by amidvidy** [comment]
Thanks, sorry for the delayed reply. Our tests automatically shutdown replsets at their conclusion, so when they fail, I usually have to hack cleanup_mprocess to not delete the data directory when I want the logs. to see what went wrong server-side.

**Comment by behackett** [comment]
I think --logappend by default is a bad idea. Over many runs of MO on Jenkins the log files are going to get enormous quickly. That will make it really difficult to track down problems in the log files. It's also useful to be able to attach the log files for a test run to a Jira ticket (there is a file size limit). If you want logappend you can pass the option in procParams.

**Comment by lovett89** [comment]
Got rid of logappend by default. Keep in mind that turning on/off logappend for any node can be done in the request itself, regardless of whatever the default is.

**Comment by behackett** [comment]
LGTM

**Pull request merged**
